default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  username: <%= ENV['DATABASE_USERNAME'] || 'djump' %>
  database: <%= ENV['DATABASE_NAME'] || 'dummy_blog_development' %>

test:
  <<: *default
  username: <%= ENV['DATABASE_USERNAME'] || 'dummy_blog' %>
  database: <%= ENV['DATABASE_NAME'] || 'dummy_blog_test' %>

production:
  <<: *default
  username: <%= ENV['DATABASE_USERNAME'] || 'dummy_blog' %>
  database: <%= ENV['DATABASE_NAME'] || 'dummy_blog_production' %>

